// client/src/components/Footer.vue
<script setup>
const year = new Date().getFullYear()
</script>

<template>
  <footer>
    <span>&copy; {{ year }} Samuel Charris Photography</span>
    <span class="footer-divider">&middot;</span>
    <a
      href="https://www.instagram.com/samuelcharriss"
      target="_blank"
      rel="noopener noreferrer"
      class="footer-link"
    >
      @samuelcharriss
    </a>
  </footer>
</template>

// react-client/src/components/footerComponent/Footer.js
import React from 'react';

const Footer = () => (
  <footer>
    <span>© {new Date().getFullYear()} Samuel Charris Photography</span>
    <span className="footer-divider">·</span>
    <a
      href="https://www.instagram.com/samuelcharriss"
      target="_blank"
      rel="noopener noreferrer"
      className="footer-link"
    >
      @samuelcharriss
    </a>
  </footer>
);

export default Footer;
